export const POST_CAPTION = "POST_CAPTION";
export const POST_TAG = "POST_TAG";
export const POST_TAGS_TO_CAPTION = "POST_TAGS_TO_CAPTION";
export const GET_TAGS = "GET_TAGS";
export const GET_CAPTIONS = "GET_CAPTIONS";
export const POST_CAPTION_WITH_TAGS = "POST_CAPTION_WITH_TAGS";
export const GET_CAPTIONS_UNDER_TAG = "GET_CAPTIONS_UNDER_TAG";
export const GET_CAPTION_WITH_TAGS = "GET_CAPTION_WITH_TAGS";
